name = "StructureSolver"
uuid = "86949bca-1401-4ad7-afb8-e041cb4ccbe4"
version = "0.1.2"
authors = ["Alexander Batrakov <batrakovalex.astro@gmail.com>"]

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
NLsolve = "4"
Roots = "2.2.10"
